/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author fabio
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GuiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        sMenuClientes = new javax.swing.JMenuItem();
        sMenuVendedores = new javax.swing.JMenuItem();
        sMenuProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        sMenuSair = new javax.swing.JMenuItem();
        menuPedido = new javax.swing.JMenu();
        sMenuEmitirPedido = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Vendas");

        menuCadastros.setText("Cadastros");

        sMenuClientes.setText("Clientes");
        sMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMenuClientesActionPerformed(evt);
            }
        });
        menuCadastros.add(sMenuClientes);

        sMenuVendedores.setText("Vendedores");
        sMenuVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMenuVendedoresActionPerformed(evt);
            }
        });
        menuCadastros.add(sMenuVendedores);

        sMenuProdutos.setText("Produtos");
        sMenuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMenuProdutosActionPerformed(evt);
            }
        });
        menuCadastros.add(sMenuProdutos);
        menuCadastros.add(jSeparator1);

        sMenuSair.setText("Sair");
        sMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMenuSairActionPerformed(evt);
            }
        });
        menuCadastros.add(sMenuSair);

        jMenuBar1.add(menuCadastros);

        menuPedido.setText("Pedido");

        sMenuEmitirPedido.setText("Emitir Pedido");
        sMenuEmitirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMenuEmitirPedidoActionPerformed(evt);
            }
        });
        menuPedido.add(sMenuEmitirPedido);

        jMenuBar1.add(menuPedido);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMenuClientesActionPerformed
        GuiCliente frm = new GuiCliente();
        frm.show();
    }//GEN-LAST:event_sMenuClientesActionPerformed

    private void sMenuEmitirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMenuEmitirPedidoActionPerformed
        GuiEmitirPedido ep = new GuiEmitirPedido();
        ep.show();
    }//GEN-LAST:event_sMenuEmitirPedidoActionPerformed

    private void sMenuVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMenuVendedoresActionPerformed
        GuiVendedor v = new GuiVendedor();
        v.show();
    }//GEN-LAST:event_sMenuVendedoresActionPerformed

    private void sMenuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMenuProdutosActionPerformed
        GuiProduto p = new GuiProduto();
        p.show();
    }//GEN-LAST:event_sMenuProdutosActionPerformed

    private void sMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMenuSairActionPerformed
        dispose();
    }//GEN-LAST:event_sMenuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuPedido;
    private javax.swing.JMenuItem sMenuClientes;
    private javax.swing.JMenuItem sMenuEmitirPedido;
    private javax.swing.JMenuItem sMenuProdutos;
    private javax.swing.JMenuItem sMenuSair;
    private javax.swing.JMenuItem sMenuVendedores;
    // End of variables declaration//GEN-END:variables
}
